services:
  - type: web
    name: pw-extractor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_URL
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: PREMIUM_LOGS
        sync: false
      - key: SUDO_USERS
        sync: false
